# -*- coding: utf-8 -*-
"""finance_project_graphs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S7Kirz5El3axYjoTGd-GgSce14W0Pz_s
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import mplfinance as mpf
sns.set_style('whitegrid')
# %matplotlib inline

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_pickle('all_banks')
display(df.head())
bank_stocks = df

tickers = ['BAC', 'C', 'GS', 'JPM', 'MS', 'WFC']

bank_stocks.xs(key='Close',axis=1,level='Stock Info').plot(figsize=(12,6))
plt.legend()
plt.title('Bank Stocks Close Price (2006-2016)')
plt.ylabel('Close Price')
plt.xlabel('Date')
plt.savefig('/content/drive/MyDrive/PortfolioProject/closing_price_linegraph.png')
plt.show()

bac_data = bank_stocks['BAC']
display(bac_data.head())

plt.figure(figsize=(12,6))
bac_data['Close'].loc['2008-01-01':'2009-01-01'].rolling(window=30).mean().plot(label='30 Day Avg')
bac_data['Close'].loc['2008-01-01':'2009-01-01'].plot(label='BAC CLOSE')
plt.legend()

plt.savefig('/content/drive/MyDrive/PortfolioProject/30_day_avg_linegraph.png')

sns.heatmap(bank_stocks.xs(key='Close',axis=1,level='Stock Info').corr(),annot=True)

plt.savefig('/content/drive/MyDrive/PortfolioProject/corr_heatmap.png')

pip install mplfinance

import pandas as pd
import mplfinance as mpf
import matplotlib.pyplot as plt

df = pd.read_pickle('all_banks')
bank_stocks = df
bac_data = bank_stocks['BAC']

mpf.plot(
    bac_data.loc['2015-01-01':'2016-01-01'],
    type='candle',
    style='yahoo',
    title='BAC Candlestick Chart (2015-2016)',
    ylabel='Price ($)',
    ylabel_lower='Volume',
    volume=True,
    figscale=1.5,
    savefig='/content/drive/MyDrive/PortfolioProject/BAC_candlestick.png'
)
plt.show()