# -*- coding: utf-8 -*-
"""finance_project_import&EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zAFvQjqBnOdLDcyeQzIB4xUmOqHKQVg3
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import datetime
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_pickle('all_banks')
display(df.head())
bank_stocks = df

bank_stocks.to_csv('/content/drive/MyDrive/PortfolioProject/bank_stocks.csv', index=True)
print("bank_stocks DataFrame exported to /content/drive/MyDrive/PortfolioProject/bank_stocks.csv")

tickers = ['BAC', 'C', 'GS', 'JPM', 'MS', 'WFC']

bank_stocks.xs(key='Close',axis=1,level='Stock Info').max()

returns = pd.DataFrame()

for tick in tickers:
    returns[tick+' Return'] = bank_stocks[tick]['Close'].pct_change()
returns.head()

returns.to_csv('/content/drive/MyDrive/PortfolioProject/returns.csv', index=True)
print("returns DataFrame exported to /content/drive/MyDrive/PortfolioProject/returns.csv")

returns[1:]
sns.pairplot(returns[1:])

plt.savefig('/content/drive/MyDrive/PortfolioProject/scatterplots.png')

# Worst Drop (4 of them on Inauguration day)
returns.idxmin()

# Best Single Day Gain
# citigroup stock split in May 2011, but also JPM day after inauguration.
returns.idxmax()

returns.std() # Citigroup riskiest

returns.loc['2015-01-01':'2015-12-31'].std() # Very similar risk profiles, but Morgan Stanley or BofA

sns.histplot(returns.loc['2015-01-01':'2015-12-31']['MS Return'], color='green', bins=100, kde=True)
plt.savefig('/content/drive/MyDrive/PortfolioProject/ms_return.png')

sns.histplot(returns.loc['2008-01-01':'2008-12-31']['C Return'],color='red',bins=100, kde=True)
plt.savefig('/content/drive/MyDrive/PortfolioProject/c_return.png')

# Volatility comparison
vol_2008 = returns.loc['2008'].std()
vol_2015 = returns.loc['2015'].std()

vol_df = pd.DataFrame({
    '2008': vol_2008,
    '2015': vol_2015
})

vol_df.plot(kind='bar', figsize=(10,6))
plt.title('Volatility Comparison: Crisis Year vs Stable Year')
plt.ylabel('Standard Deviation of Daily Returns')

plt.savefig('/content/drive/MyDrive/PortfolioProject/volatility_comparison.png')
plt.show()